name: mad_weatherize
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_core: ^3.10.1
  http: ^1.2.2
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/notext.jpg
